<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    private array $cities = [
        ['name' => 'Almaty'],
        ['name' => 'Astana'],
        ['name' => 'Shymkent'],
        ['name' => 'Karaganda'],
        ['name' => 'Aktobe'],
        ['name' => 'Taraz'],
        ['name' => 'Pavlodar'],
        ['name' => 'Ust-Kamenogorsk'],
        ['name' => 'Semey'],
        ['name' => 'Kostanay'],
        ['name' => 'Kyzylorda'],
        ['name' => 'Uralsk'],
        ['name' => 'Petropavlovsk'],
        ['name' => 'Aktau'],
        ['name' => 'Temirtau'],
        ['name' => 'Turkestan'],
        ['name' => 'Atyrau'],
        ['name' => 'Kokshetau'],
        ['name' => 'Taldykorgan'],
        ['name' => 'Ekibastuz'],
        ['name' => 'Rudny'],
        ['name' => 'Zhezkazgan'],
        ['name' => 'Zhanaozen'],
        ['name' => 'Balhash'],
        ['name' => 'Kentau'],
        ['name' => 'Saryagash'],
        ['name' => 'Kapchagay'],
        ['name' => 'Zyryanovsk'],
        ['name' => 'Aksu'],
        ['name' => 'Arkalyk'],
        ['name' => 'Lisakovsk'],
        ['name' => 'Shu'],
        ['name' => 'Stepnogorsk'],
        ['name' => 'Zhetysay'],
        ['name' => 'Talgar'],
        ['name' => 'Zharkent'],
        ['name' => 'Taldyqorghan'],
        ['name' => 'Shchuchinsk'],
        ['name' => 'Arys'],
        ['name' => 'Shemonaikha'],
        ['name' => 'Shakhtinsk'],
        ['name' => 'Ayagoz'],
        ['name' => 'Shalqar'],
        ['name' => 'Esik'],
        ['name' => 'Khromtau'],
        ['name' => 'Aral'],
        ['name' => 'Aksu'],
        ['name' => 'Kandyagash'],
        ['name' => 'Shieli'],
        ['name' => 'Kapshagay'],
        ['name' => 'Zhanatas'],
        ['name' => 'Zaysan'],
        ['name' => 'Balyqshy'],
        ['name' => 'Kachiry'],
        ['name' => 'Komsomolets'],
        ['name' => 'Kachar'],
        ['name' => 'Kazaly'],
        ['name' => 'Karasu'],
        ['name' => 'Karkaraly'],
        ['name' => 'Kaztalovka'],
        ['name' => 'Kokpekty'],
        ['name' => 'Kulan'],
        ['name' => 'Kurchatov'],
        ['name' => 'Leninogorsk'],
        ['name' => 'Lenger'],
        ['name' => 'Makinsk'],
        ['name' => 'Mamlyutka'],
        ['name' => 'Mikhaylovka'],
        ['name' => 'Novodolinskoe'],
        ['name' => 'Novopokrovka'],
        ['name' => 'Oskemen'],
        ['name' => 'Pavlodar'],
        ['name' => 'Priozersk'],
        ['name' => 'Ridder'],
        ['name' => 'Rudnyi'],
        ['name' => 'Saran'],
        ['name' => 'Sarkand'],
        ['name' => 'Satpayev'],
        ['name' => 'Serebryansk'],
        ['name' => 'Shardara'],
        ['name' => 'Shemonaikha'],
        ['name' => 'Shieli'],
        ['name' => 'Shonzhy'],
        ['name' => 'Serebryansk'],
        ['name' => 'Sarkand'],
        ['name' => 'Saran'],
        ['name' => 'Rudnyi'],
        ['name' => 'Ridder'],
        ['name' => 'Priozersk'],
        ['name' => 'Pavlodar'],
        ['name' => 'Oskemen'],
        ['name' => 'Novopokrovka'],
        ['name' => 'Novodolinskoe'],
        ['name' => 'Mikhaylovka'],
        ['name' => 'Mamlyutka'],
        ['name' => 'Makinsk'],
        ['name' => 'Lenger'],
        ['name' => 'Len'],

    ];
    public function run()
    {
        foreach ($this->cities as $city) {
            City::create($city);
        }
    }
}
